apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "f5-bigip-ingress.fullname" . }}
  namespace: {{ .Values.ingress.namespace }}
  labels:
    app: {{ template "f5-bigip-ingress.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  backend:
    serviceName: {{ .Values.ingress.backend.serviceName }}
    servicePort: {{ .Values.ingress.backend.servicePort }}
  
